import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Container } from "./components/Container";
import { Header } from "./components/Header";

export const metadata: Metadata = {
  title: "GoLeadger Streaming Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Container>
          <Header />
          <main>{children}</main> {/* Renderize o conteúdo aqui */}
        </Container>
      </body>
    </html>
  );
}
