import { Toaster } from 'sonner';
import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import { StreamingProvider } from '../context/StreamingContext';
import { Container } from './components/Container';
import { Header } from './components/Header';

export const metadata: Metadata = {
  title: 'GoLeadger Streaming Music',
  description: 'Generated by create next app',
};

// Defina o QueryClient fora do código marcado com 'use client'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StreamingProvider>
      <html lang="en">
        <body className="antialiased">
          <Container>
            <Header />
            <main>{children}</main>
          </Container>
          <Toaster />
        </body>

      </html>
    </StreamingProvider>
  );
}
